### PR TITLE
implementation of the try-with-resource added in Java 7 to close the connection automatically

### PR DESCRIPTION
**Pull request by clairtonluz**

### CODE REVIEW

**Comment by GideonLeGrange** [comment]
Thank you for this. I'm not against implementing ```Closable``` but I want to have some clarity on the following first:

If I understand the Oracle documentation correctly, we actually want to implement [AutoCloseable](http://docs.oracle.com/javase/7/docs/api/java/lang/AutoCloseable.html) which is available from 1.7, rather that ```Closeable``` which is available from 1.5 and was originally intended for streams.  

See this [tutorial](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html). 

At the end of that document, is the following:

>See the Javadoc of the AutoCloseable and Closeable interfaces for a list of classes that implement either of these interfaces. The Closeable interface extends the AutoCloseable interface. The close method of the Closeable interface throws exceptions of type IOException while the close method of the AutoCloseable interface throws exceptions of type Exception. Consequently, subclasses of the AutoCloseable interface can override this behavior of the close method to throw specialized exceptions, such as IOException, or no exception at all.

I think going for ```AutoCloseable``` is also better because we can just throw ```MikrotikApiException``` without having to wrap the exception in an IOException. 

What is your opinion?

Gideon

**Comment by clairtonluz** [comment]
You're right. Later I will implement.

**Comment by GideonLeGrange** [comment]
I've implemented ```AutoCloseable``` and pushed to master.

**Comment by clairtonluz** [comment]
?

**Comment by clairtonluz** [comment]
You don't accept contribution?

**Comment by GideonLeGrange** [comment]
I do accept contributions. I just implemented AutoCloseable rather than wait until later. I did not intend any offence.

**Comment by clairtonluz** [comment]
Ok. What can I do to contruibe to the project?

**Pull request closed without merging**
